version: "1"

services:
  sonarqube:
    image: sonarqube
    expose:
      - 9000
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - /tmp/sonar/sonarqube_conf:/opt/sonarqube/conf
      - /tmp/sonar/sonarqube_data:/opt/sonarqube/data
      - /tmp/sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - /tmp/sonar/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 5000M
        reservations:
          cpus: "0.2"
          memory: 2000M

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /tmp/sonar/postgresql:/var/lib/postgresql
      - /tmp/sonar/postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
